### ISSUE TITLE
Tracking issue for multiple packages per build manifest

### ISSUE THREAD

**Issue by Arignir** [raven-os/nbuild#11]
Check list:

* [ ] Find a syntax to indicate the different built packages
* [ ] Use the same repository to build the different packages
* [ ] Create different `data.tar.gz` and `manifest.toml` per package, in their correct folder.

The typical use case is `mylib` and `mylib-dev`, containing the headers and documentation for `mylib`. We want both of them to be created from the very same build to ensure they are 100% compatible with each other.

**Comment by Arignir** [comment]
Pull request #14 solves this issue.
I also explained there the solutions to the problematic raised above.

I'll close this only when/if the PR is merged.

**Comment by Arignir** [comment]
Fixed with #14 .
