### ISSUE TITLE
Tracking issues for tests

### ISSUE THREAD

**Issue by melis-m** [raven-os/nbuild#12]
Checklist:
- [ ] Integrate with Travis
- [ ] Add unit tests
- [ ] Add integration tests
