### ISSUE TITLE
Tracking issue for automated validity check resolver

### ISSUE THREAD

**Issue by melis-m** [raven-os/nbuild#23]
Add a way to allow resolving of problems found by the checker

Modes:
- [ ] Show a diff between the actual and a recommendation
- [ ] Automatically resolve (and show how) all problems
- [ ] Allow manual editing of the problem

Problems:
- [ ] File permissions
- [ ] Files are not in the correct split
- [ ] Invalid description
- [ ] Invalid dependencies
- [ ] Missing dependencies
- [ ] Files not in correct folder
