### ISSUE TITLE
Tracking issue for Docker image

### ISSUE THREAD

**Issue by melis-m** [raven-os/nbuild#5]
Checklist:
- [ ] Compile the necessary packages on the host
    - [ ] Essentials
    - [ ] Nest
    - [ ] nbuild
- [ ] Create a Docker image from these
- [ ] Recompile the necessary packages from the docker container
- [ ] Recreate a Docker image from these packages
- [ ] Recompile the necessary packages from the docker container
- [ ] Recreate a Docker image from these packages

**Comment by Arignir** [comment]
This shouldn't be hard since the ISO is now operational. Basically boils down to `nest install essentials` (more or less).
