### ISSUE TITLE
Tracking issue for the Compilation Standard Library

### ISSUE THREAD

**Issue by melis-m** [raven-os/nbuild#6]
Tracking issue for the Compilation Standard Library:

- [x] Prelude
- [x] Provide an abstraction for a Build Manifest, a Package and a Build
- [x] Provide functions to fetch a file, patch the source tree and execute commands.
- [x] Provide the `autootols` template
- [x] Generate the name of packages automatically
- [x] Manage packages' dependencies automatically
- [x] Ensure the libraries are executable
- [x] Install build dependencies building the package
- [x] Support the creation of different packages from a single build manifest (See #11 )
